clusters:
  - name: ikkem-hpc
    ssh:
      host: ikkem-hpc
      socks_port: 10801

    lambdas:
      - name: echo
        forward_to: http://{NODE_NAME}:8080/
        cwd: ./tmp-jql
        script: |
          #!/bin/bash
          #SBATCH -N 1
          #SBATCH --job-name=echo
          #SBATCH --partition=cpu
          set -e
          timeout 30 python3 -m http.server 8080

    job_queue:
      slurm: {}
